export const UrlConstants ={
    fileuploadurl:"FileUploads",
    companyDetails:"AddOrUpdateCompanyDetails",
    getCompanyDetails:"GetAllCompanyDetails",
    projectDetails:"FileUploads",
    projectType:"GetProjectTypes",
    customerDetailsById:"GetProjectDetailsBySearchId",
    getAllProjectDetails:"GetAllProjectDetails",
    updateProjcetInfo:"UpdateProjectInfo",
    getProjectDetailsByProjectId:"GetProjectDetailsByProjectId",
    addProjectType:"AddProjectType",
    getUserDetailsByUserName:"GetUserDetailsByUserName",
    submitUserDetails:"AddBookNowUserDetails",
    sendRequestQuoteDetails:"AddRequestQuoteDetails",
    getAllRequestQuoteDetails:"GetAllRequestQuoteDetails",
    getRequestQuoteDetailsById:"GetRequestQuoteDetailsById",
    updateRequestQuoteDetails:"UpdateRequestQuoteDetails",
    getAllBookNowDetailsById:"GetAllBookNowDetailsById",
    getAllBookNowDetails:"GetAllBookNowDetails",
    updateBookNowDetails:"UpdateBookNowDetails",
}; //no NEED TO USE Controller Name always as we are using attribute routing.
